version: "3.7"

services:
  app:
    image: ghcr.io/beeracademy/game
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.game-academy-beer.rule=Host(`game.academy.beer`)
      - traefik.http.services.game-academy-beer.loadbalancer.server.port=80

networks:
  traefik:
    external: true
