name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: ghcr.io/beeracademy/game

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t "$DOCKER_IMAGE_NAME" .
          docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_NAME:$GITHUB_SHA"

      - name: Publish image to ghcr.io
        run: |
          echo "$GHCR_PASSWORD" | docker login ghcr.io --username "$GHCR_USERNAME" --password-stdin
          docker push "$DOCKER_IMAGE_NAME"
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}

      - name: Deploy image to production
        run: curl --fail -X POST "$WEBHOOK_URL"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
